/*DROP DATABASE AppKinsonDB;*/

CREATE DATABASE AppKinsonDB;


USE AppKinsonDB;

CREATE TABLE users(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(60) NOT NULL,
    TYPE VARCHAR(60) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE doctors(
    ID_USER INT(11) NOT NULL,
    NAME VARCHAR(50),
    PHOTOPATH VARCHAR(255),
    FOREIGN KEY (ID_USER) REFERENCES users(ID) ON DELETE CASCADE 
);

CREATE TABLE patients(
    ID_USER INT(11) NOT NULL,
    NAME VARCHAR(50),
    PHOTOPATH VARCHAR(255),
    FOREIGN KEY (ID_USER) REFERENCES users(ID) ON DELETE CASCADE 
);

CREATE TABLE carers(
    ID_USER INT(11) NOT NULL,
    NAME VARCHAR(50),
    PHOTOPATH VARCHAR(255),
    FOREIGN KEY (ID_USER) REFERENCES users(ID) ON DELETE CASCADE 
);

CREATE TABLE requestlinkdoctortopatient(
    ID_DOCTOR INT(11) NOT NULL,
    ID_PATIENT INT(11) NOT NULL,
    FOREIGN KEY (ID_DOCTOR) REFERENCES doctors(ID_USER) ON DELETE CASCADE ,
    FOREIGN KEY (ID_PATIENT) REFERENCES patients(ID_USER) ON DELETE CASCADE ,
    PRIMARY KEY (ID_DOCTOR,ID_PATIENT)
);

CREATE TABLE patientxdoctor(
    ID_DOCTOR INT(11) NOT NULL,
    ID_PATIENT INT(11) NOT NULL,
    FOREIGN KEY (ID_DOCTOR) REFERENCES doctors(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (ID_PATIENT) REFERENCES patients(ID_USER) ON DELETE CASCADE,
    PRIMARY KEY (ID_DOCTOR,ID_PATIENT)
);

CREATE TABLE patientxcarer(
    ID_CARER INT(11) NOT NULL,
    ID_PATIENT INT(11) NOT NULL,
    FOREIGN KEY (ID_CARER) REFERENCES carers(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (ID_PATIENT) REFERENCES patients(ID_USER) ON DELETE CASCADE,
    PRIMARY KEY (ID_CARER,ID_PATIENT)
);

CREATE TABLE requestlinkcarertopatient(
    ID_CARER INT(11) NOT NULL,
    ID_PATIENT INT(11) NOT NULL,
    FOREIGN KEY (ID_CARER) REFERENCES carers(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (ID_PATIENT) REFERENCES patients(ID_USER) ON DELETE CASCADE,
    PRIMARY KEY (ID_CARER,ID_PATIENT)
);

CREATE TABLE symptomsformpatient (
    ID_PATIENT INT(11) NOT NULL,
    Q1 VARCHAR(50) NOT NULL,
    Q2 VARCHAR(50) NOT NULL,
    formdate DATETIME NOT NULL,
    pathvideo VARCHAR(50),
    FOREIGN KEY (ID_PATIENT) REFERENCES patients(ID_USER) ON DELETE CASCADE,
    PRIMARY KEY (ID_PATIENT,formdate)
);

CREATE TABLE patientxsymptomsform(
    ID_PATIENT INT(11) NOT NULL,
    DATE_FORM DATETIME,
    FOREIGN KEY (ID_PATIENT) REFERENCES patients(ID_USER) ON DELETE CASCADE,
    PRIMARY KEY (DATE_FORM,ID_PATIENT)
);

CREATE TABLE emotionalformpatient (
    ID_PATIENT INT(11) NOT NULL,
    Q1 INT(11) NOT NULL,
    Q2 INT(11) NOT NULL,
    Q3 INT(11) NOT NULL,
    Q4 INT(11) NOT NULL,
    Q5 INT(11) NOT NULL,
    Q6 INT(11) NOT NULL,
    Q7 INT(11) NOT NULL,
    Q8 INT(11) NOT NULL,
    Q9 INT(11) NOT NULL,
    Q10 INT(11) NOT NULL,
    Q11 INT(11) NOT NULL,
    Q12 INT(11) NOT NULL,
    Q13 INT(11) NOT NULL,
    Q14 INT(11) NOT NULL,
    Q15 INT(11) NOT NULL,
    Q16 INT(11) NOT NULL,
    Q17 INT(11) NOT NULL,
    Q18 INT(11) NOT NULL,
    Q19 INT(11) NOT NULL,
    Q20 INT(11) NOT NULL,
    Q21 INT(11) NOT NULL,
    Q22 INT(11) NOT NULL,
    Q23 INT(11) NOT NULL,
    Q24 INT(11) NOT NULL,
    Q25 INT(11) NOT NULL,
    Q26 INT(11) NOT NULL,
    Q27 INT(11) NOT NULL,
    Q28 INT(11) NOT NULL,
    Q29 INT(11) NOT NULL,
    Q30 INT(11) NOT NULL,
    date DATETIME NOT NULL,
    FOREIGN KEY (ID_PATIENT) REFERENCES patients(ID_USER) ON DELETE CASCADE,
    PRIMARY KEY (ID_PATIENT,date)
);

CREATE TABLE medicinealarmpatient (
    ID_PATIENT INT(11) NOT NULL,
    id VARCHAR(50) NOT NULL,
    title VARCHAR(50),
    alarmDateTime DATETIME,
    alarmTime TIME NOT NULL,
    isPending BOOLEAN,
    FOREIGN KEY (ID_PATIENT) REFERENCES patients(ID_USER) ON DELETE CASCADE,
    PRIMARY KEY (ID_PATIENT,id)
);
