DROP DATABASE AppKinsonDB;

CREATE DATABASE AppKinsonDB;


USE AppKinsonDB;

CREATE TABLE users(
    ID INT(11) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    TYPE VARCHAR(60) NOT NULL
);


ALTER TABLE users ADD PRIMARY KEY(ID);

ALTER TABLE users MODIFY ID INT(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT = 1;