DROP DATABASE AppKinsonDB;

CREATE DATABASE AppKinsonDB;


USE AppKinsonDB;

CREATE TABLE users(
    ID INT(11) NOT NULL AUTO_INCREMENT,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(60) NOT NULL,
    TYPE VARCHAR(60) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE doctors(
    ID_USER INT(11) NOT NULL,
    NAME VARCHAR(50),
    PHOTOPATH VARCHAR(255),
    FOREIGN KEY (ID_USER) REFERENCES users(ID)
);

CREATE TABLE patients(
    ID_USER INT(11) NOT NULL,
    NAME VARCHAR(50),
    PHOTOPATH VARCHAR(255),
    FOREIGN KEY (ID_USER) REFERENCES users(ID)
);

CREATE TABLE carers(
    ID_USER INT(11) NOT NULL,
    NAME VARCHAR(50),
    PHOTOPATH VARCHAR(255),
    FOREIGN KEY (ID_USER) REFERENCES users(ID)
);

CREATE TABLE patientxdoctor(
    ID_DOCTOR INT(11) NOT NULL,
    ID_PATIENT INT(11) NOT NULL,
    FOREIGN KEY (ID_DOCTOR) REFERENCES doctors(ID_USER),
    FOREIGN KEY (ID_PATIENT) REFERENCES patients(ID_USER),
    PRIMARY KEY (ID_DOCTOR,ID_PATIENT)
);

CREATE TABLE requestlinkdoctortopatient(
    ID_DOCTOR INT(11) NOT NULL,
    ID_PATIENT INT(11) NOT NULL,
    FOREIGN KEY (ID_DOCTOR) REFERENCES doctors(ID_USER) ON DELETE CASCADE ,
    FOREIGN KEY (ID_PATIENT) REFERENCES patients(ID_USER) ON DELETE CASCADE ,
    PRIMARY KEY (ID_DOCTOR,ID_PATIENT)
);

CREATE TABLE requestlinkcarertopatient(
    ID_CARER INT(11) NOT NULL,
    ID_PATIENT INT(11) NOT NULL,
    FOREIGN KEY (ID_CARER) REFERENCES carers(ID_USER) ON DELETE CASCADE,
    FOREIGN KEY (ID_PATIENT) REFERENCES patients(ID_USER) ON DELETE CASCADE,
    PRIMARY KEY (ID_CARER,ID_PATIENT)
);