const jwtkey = "Bearer ";
const addUserUrl = '/api/registro';
const authURL = '/api/login';
const linkUserUnrelatedURL = '/api/doctor/patients/unrelated';
const linkUserURL = '/api/relate/';
const linkUserRelatedURL = '/api/doctor/patients/related';
const modifyNameOfUserURL = '/api/users/';
//String endpointBack = 'http://18.191.132.173:9001';
String endpointBack = 'http://192.168.0.16:8000';
